// core/tokenizers.js
// Offtoco — GPL-3.0-or-later — PacifAIst/Offtoco
// Universal module: works in Node.js and the browser (Vite bundle).
// Zero WASM — all three tokenisers are pure JS.
//
// Claude vocab is loaded from core/claude-vocab.js, which is generated
// by scripts/gen-claude-vocab.js (runs automatically on pnpm install).
// Counts are bit-for-bit identical to @anthropic-ai/tokenizer.
//
// Exports:
//   initTokenizers()  — await once before countAll()
//   isReady()         — boolean
//   countAll(text)    — { gpt, claude, gemini }
//   count(text)       — async convenience wrapper

import { Tiktoken }      from 'js-tiktoken/lite';
import o200k_base        from 'js-tiktoken/ranks/o200k_base';
import claudeJson        from './claude-vocab.js';        // generated by postinstall
import { fromPreTrained } from '@lenml/tokenizer-gemini';

let _gptEnc    = null;
let _claudeEnc = null;
let _geminiTok = null;
let _ready     = false;

export async function initTokenizers() {
  if (_ready) return;
  _gptEnc    = new Tiktoken(o200k_base);
  _claudeEnc = new Tiktoken(claudeJson);
  _geminiTok = fromPreTrained();
  _ready = true;
}

export function isReady() { return _ready; }

export function countAll(text) {
  if (!_ready) throw new Error('Offtoco: call await initTokenizers() before countAll()');
  if (typeof text !== 'string') text = String(text ?? '');
  return {
    gpt:    _gptEnc.encode(text).length,
    claude: _claudeEnc.encode(text, 'all').length,
    gemini: _geminiTok.encode(text, { add_special_tokens: false }).length,
  };
}

export async function count(text) {
  if (!_ready) await initTokenizers();
  return countAll(text);
}
